name: Deploy GH Pages

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.18.0"

      # - name: Get Raid Helper Events
      #   env:
      #     RH_SERVERID: ${{ secrets.RH_SERVERID }}
      #     RH_APIKEY: ${{ secrets.RH_APIKEY }}
      #   run: |
      #     go run scripts/main.go

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
